ServerName localhost

Alias /otrs-web /opt/otrs/var/httpd/htdocs/
ScriptAlias /otrs/ /opt/otrs/bin/cgi-bin/

<Directory "/opt/otrs/bin/cgi-bin">
    AllowOverride None
    Options +ExecCGI -Includes
    Require all granted
    AddHandler cgi-script .pl
</Directory>

<Directory "/opt/otrs/var/httpd/htdocs">
    AllowOverride None
    Require all granted
</Directory>
