ServerName localhost

ScriptAlias /otrs/ "/opt/otrs/bin/cgi-bin/"
Alias /otrs-web/ "/opt/otrs/var/httpd/htdocs/"

<Directory "/opt/otrs/bin/cgi-bin/">
    AllowOverride None
    Options +ExecCGI +FollowSymLinks
    DirectoryIndex index.pl
    AddHandler cgi-script .pl
    Require all granted
</Directory>

<Directory "/opt/otrs/var/httpd/htdocs/">
    AllowOverride None
    Options +FollowSymLinks
    DirectoryIndex index.html
    Require all granted
</Directory>
